version: 2

updates:
  - package-ecosystem: "cargo"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        dependency-type: "production"
      dev-dependencies:
        dependency-type: "development"
